18 easy improvements from the first feedback of the lgs
JDAV-Bayern/fahrtkostenabrechnung pull request #23
Opened 2024-02-10 18:22 UTC by josephhirsch

2024-02-11 17:11 UTC, simon-lgb requested changes
I added some suggestions, but most importantly, the validation of the course code is incorrect.

2024-02-11 17:11 UTC, simon-lgb commented on src/app/personal-information-component/personal-information-component.component.html
> +            Diese Kursnummer sieht falsch aus. Kursnummern von Kursen der JDAV Bayern folgen dem Format BXXXFB oder BXXXAM. Bitte überprüfe die Kursnummer noch einmal und stelle sicher, dass Du einen
It can end in "GA" as well. We could add a more specific message when codes starting with "J" are entered to explain that this is the wrong organisation.

2024-02-11 17:11 UTC, simon-lgb commented on src/app/personal-information-component/personal-information-component.component.html
> +        <label for="courseDate">Kursdatum</label>
Should this field be removed?

2024-02-11 17:11 UTC, simon-lgb commented on src/app/personal-information-component/personal-information-component.component.html
> +        <label for="courseLocation">Kursort</label>
Should this field be removed?

2024-02-11 17:11 UTC, simon-lgb commented on src/app/personal-information-component/personal-information-component.component.ts
> +        [Validators.required, Validators.pattern(/B\d+(FB|AM)/)]
The course code can end in "GA"

2024-02-11 17:11 UTC, simon-lgb commented on src/app/reimbursement.validation.service.ts
> +      if (reimbursement.courseDetails.id.match(/B\d+(FB|AM)/) === null)
Once again, GA is possible here and in the following lines

2024-02-11 17:11 UTC, simon-lgb commented on src/app/expenses-collection-component/add-expense-modal/add-expense-modal.component.html
>      <button (click)="chooseBikeExpense()" class="gray-button">
Should we hide this for travel during the course as well?

2024-02-14 09:27 UTC, josephhirsch commented on src/app/personal-information-component/personal-information-component.component.html
> +        <label for="courseLocation">Kursort</label>
yes

2024-02-14 09:28 UTC, josephhirsch commented on src/app/personal-information-component/personal-information-component.component.html
> +        <label for="courseDate">Kursdatum</label>
yes

2024-02-14 09:28 UTC, josephhirsch commented on src/app/expenses-collection-component/add-expense-modal/add-expense-modal.component.html
>      <button (click)="chooseBikeExpense()" class="gray-button">
yes

2024-02-29 22:35 UTC, closed without merging